/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 destiny_model/hunter.gltf
Author: Daniel Cardona (https://sketchfab.com/DanielCardonaArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/destiny-2-character-bust-a56b08cf4d6948bdbdd1f7cd7a12d98a
Title: Destiny 2 Character Bust
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Hunter = ({ props, isMobile }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./destiny_model/hunter.gltf')
  const { actions, names } = useAnimations(animations, group)

  useEffect(() => {
    if(isMobile) {
      actions[names[0]].reset().fadeIn(0.5).stop()
    } else {
      actions[names[0]].reset().fadeIn(0.5).play()
    }
  }, [isMobile])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="cde323fd0e0c4aacbabae784c3d8b435fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group name="pCylinder1" position={[0, 9, -17.83]} scale={[31.36, 28.5, 31.36]}>
                    <mesh name="pCylinder1_smokeM_0" geometry={nodes.pCylinder1_smokeM_0.geometry} material={materials.smokeM} />
                  </group>
                  <group name="polySurface4" position={[-6.22, -3.29, -0.19]}>
                    <mesh name="polySurface4_BustM_0" geometry={nodes.polySurface4_BustM_0.geometry} material={materials.BustM} />
                  </group>
                  <group name="polySurface3" position={[-7.02, -5.39, -0.19]}>
                    <mesh name="polySurface3_BustM_0" geometry={nodes.polySurface3_BustM_0.geometry} material={materials.BustM} />
                  </group>
                  <group name="polySurface2" position={[-7.67, -6.4, -0.19]}>
                    <mesh name="polySurface2_BustM_0" geometry={nodes.polySurface2_BustM_0.geometry} material={materials.BustM} />
                  </group>
                  <group name="polySurface1" position={[-6.37, -4.49, -0.19]}>
                    <mesh name="polySurface1_BustM_0" geometry={nodes.polySurface1_BustM_0.geometry} material={materials.BustM} />
                  </group>
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="bust" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.BustM} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Hunter

useGLTF.preload('./destiny_model/hunter.gltf')
// ./destiny_model
